truncate dungeon;
-- set foreign_key_checks = 1;
insert into dungeon (id) values ('1');
insert into dungeon (id) values ('2');
insert into dungeon (id) values ('3');
insert into dungeon (id) values ('4');
insert into dungeon (id) values ('5');
insert into dungeon (id) values ('6');
insert into dungeon (id) values ('7');
insert into dungeon (id) values ('8');
insert into dungeon (id) values ('9');
insert into dungeon (id) values ('10');